browser=chrome;
search=[name='q']
userName=#identifierId

##Banking

banking_url = https://way2automation.com/angularjs-protractor/banking/#/login

#Customer_login

cst_login = button[ng-click='customer()']

#Bank manager_login

bankManager_login = button[ng-click='manager()']

add_cst_btn = button[ng-click='addCust()']

open_account_btn = button[ng-click='openAccount()']

customers_btn = button[ng-click='showCust()']

#addCustomer

first_name = input[ng-model='fName']

last_name = input[ng-model='lName']

post_code = input[ng-model='postCd']

customer_submit = button[type='submit']

#openAccount

user_select = #userSelect
currency_select = #currency
process_submit = button[type='submit']
